nucleos_dompdf:
    defaults:
        defaultFont: 'Arial'
        chroot: '%kernel.project_dir%/public' # See https://github.com/dompdf/dompdf/wiki/Usage#options
        isRemoteEnabled: true
        isHtml5ParserEnabled: true
        logOutputFile: '' # Prevent creating `/tmp/log.htm` which causes problems in some server configurations
