parameters:
    produit_images_directory: '%kernel.project_dir%/public/uploads/produits'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\StripeService:
        arguments:
            $secretKey: '%env(STRIPE_SECRET_KEY)%'

    App\Service\RecaptchaService:
        arguments:
            $secretKey: '%env(RECAPTCHA_SECRET_KEY)%'

    App\Service\PdfTicketService:
        arguments:
            $apdfApiKey: '%env(APDF_API_KEY)%'

    Symfony\Component\Security\Http\Authenticator\FormLoginAuthenticator:
        alias: security.authenticator.form_login.main
        public: true

    geocoder.http_client:
        class: GuzzleHttp\Client

    geocoder.google_maps:
        class: Geocoder\Provider\GoogleMaps\GoogleMaps
        arguments:
            - '@geocoder.http_client'
            - null
            - '%env(GOOGLE_MAPS_API_KEY)%'

    Geocoder\StatefulGeocoder:
        arguments:
            - '@geocoder.google_maps'
            - 'fr'